# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StackApiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500)),
                ('link', models.CharField(max_length=2500)),
                ('encrp_title', django_cryptography.fields.encrypt(models.CharField(max_length=1500))),
                ('encrp_link', django_cryptography.fields.encrypt(models.CharField(max_length=2500))),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
